---
title: "temperature"
author: "Shengye (Tony) Niu"
date: "14/04/2021"
output: html_document
---

```{r}
library(plotly)
library(tidyverse)
library(tidyr)
table <- read.delim("/data/temperature.txt", header=FALSE)
table <- data.frame(table)

data <- 
  table %>% 
  slice(5:length(table[,1])) %>% 
  separate(V1, c("Year", "No_Smoothing", "Lowess"), sep="     ")

data$No_Smoothing = as.numeric((data$No_Smoothing))
data$Lowess = as.numeric((data$Lowess))

head(data)

fig <- plot_ly(data, x = ~Year, y = ~Lowess, type = 'scatter', 
               mode = 'lines', showlegend=TRUE, color = I("#EF476F"), width=700, height=595)
fig <- fig %>% layout(title = list(text = paste0('... and global temperatures continue to rise',
                                    '<br>',
                                    '<sup>',
                                    'Global Land-Ocean Temperature Index',
                                    '</sup>'), 
                                   x = 0.1,
                                   y = 0.9,
                                   font = list(
                                     family = "arial",
                                     size = 20)),
                      margin = list(l = 100,
                                    r = 50,
                                    b = 100,
                                    t = 100,
                                    pad = 20), 
         paper_bgcolor="#d2d2d1", plot_bgcolor="#d2d2d1",
         xaxis = list(title = "Year",
                      gridcolor = "white",
                      showgrid = TRUE,
                      showline = FALSE,
                      tickvals = list(1880, 1900, 1920, 1940, 1960, 1980, 2000, 2020),
                      zeroline = FALSE,
                      tickfont = list(family = "arial", size = 14),
                      titlefont = list(family = "arial", size = 14)),
         yaxis = list(title = "Temperature Anomaly (C)",
                      gridcolor = "white",
                      showgrid = TRUE,
                      showline = FALSE,
                      zeroline = FALSE,
                      tickfont = list(family = "arial", size = 14),
                      titlefont = list(family = "arial", size = 14))) 

fig %>% 
    add_annotations(text="Data source: NASA's Goddard Institute for Space Studies (GISS)", 
                    xref='paper',
                    yref='paper',
                    x=0.65,y=-0.22,
                    showarrow=FALSE, 
                    font = list(family = "arial", size = 14))

```


```{r}

library("readxl")

cat <- read_excel("/Users/tony_niu/Desktop/University/STA313/STA313\ Final\ Project/Product/All\ codes/DataVisProject/TN/data/CAT.xlsx")
cat <- cat[-c(1, 2, 3, 4, 5, 6, 7), ]

cat[1, 2] <- '0'

years <- as.numeric(t(cat[1,-c(1, 2)]))

ar5_high <- as.numeric(t(cat[2,-c(1, 2)]))
ar5_low <- as.numeric(t(cat[3,-c(1, 2)]))
current_high <- as.numeric(t(cat[4,-c(1, 2)]))
current_low <- as.numeric(t(cat[5,-c(1, 2)]))
pledge_high <- as.numeric(t(cat[6,-c(1, 2)]))
pledge_low <- as.numeric(t(cat[7,-c(1, 2)]))
opt <- as.numeric(t(cat[8,-c(1, 2)]))
c2_high <- as.numeric(t(cat[9,-c(1, 2)]))
c2_med <- as.numeric(t(cat[10,-c(1, 2)]))
c2_low <- as.numeric(t(cat[11,-c(1, 2)]))
c15_high <- as.numeric(t(cat[12,-c(1, 2)]))
c15_med <- as.numeric(t(cat[13,-c(1, 2)]))
c15_low <- as.numeric(t(cat[14,-c(1, 2)]))
historical <- as.numeric(t(cat[15,-c(1, 2)]))

data <- data.frame("years" = years, 
                   "ar5_high" = as.numeric(ar5_high), "ar5_low" = as.numeric(ar5_low), 
                   "current_high" = as.numeric(current_high), "current_low" = as.numeric(current_low),
                   "pledge_high" = as.numeric(pledge_high), "current_low" = as.numeric(pledge_low),
                   "opt" = as.numeric(opt),
                   "c2_high" = as.numeric(c2_high), "c2_med" = as.numeric(c2_med), "c2_low" = as.numeric(c2_low),
                   "c15_high" = as.numeric(c15_high), "c15_med" = as.numeric(c15_med), "c15_low" = as.numeric(c15_low),
                   "historical" = as.numeric(historical))

data$years <- factor(data$years, levels = data[["years"]])


fig <- plot_ly(data, x = ~years, y = ~ar5_high, type = 'scatter', mode = 'lines',
        line = list(color = '739099', width = 0),
        showlegend = FALSE, width=760, height=595)
fig <- fig %>% add_trace(y = ~ar5_low, type = 'scatter', mode = 'lines',
            fill = 'tonexty', fillcolor='739099', line = list(color = '739099', width = 0),
            showlegend = TRUE, name = list(text = "Baseline:\n4.1 - 4.8 C"))

fig <- fig %>% add_trace(x = ~years, y = ~current_high, type = 'scatter', mode = 'lines',
        line = list(color = '118ab2', width = 0),
        showlegend = FALSE)
fig <- fig %>% add_trace(y = ~current_low, type = 'scatter', mode = 'lines',
            fill = 'tonexty', fillcolor='118ab2', line = list(color = '118ab2', width = 0),
            showlegend = TRUE, name = list(text = "Current policies:\n2.7 - 3.1 C"))

fig <- fig %>% add_trace(x = ~years, y = ~pledge_high, type = 'scatter', mode = 'lines',
        line = list(color = '0cb0a9', width = 0),
        showlegend = FALSE)
fig <- fig %>% add_trace(y = ~pledge_low, type = 'scatter', mode = 'lines',
            fill = 'tonexty', fillcolor='0cb0a9', line = list(color = '0cb0a9', width = 0),
            showlegend = TRUE, name = list(text = "Pledges & targets:\n2.3 - 2.6 C"))

fig <- fig %>% add_trace(x = ~years, y = ~c2_high, type = 'scatter', mode = 'lines',
        line = list(color = 'ffd166', width = 0),
        showlegend = FALSE)
fig <- fig %>% add_trace(y = ~c2_low, type = 'scatter', mode = 'lines',
            fill = 'tonexty', fillcolor='ffd166', line = list(color = 'ffd166', width = 0),
            showlegend = TRUE, name = list(text = "2 C consistent"))

fig <- fig %>% add_trace(x = ~years, y = ~c15_high, type = 'scatter', mode = 'lines',
        line = list(color = '83d483', width = 0),
        showlegend = FALSE)
fig <- fig %>% add_trace(y = ~c15_low, type = 'scatter', mode = 'lines',
            fill = 'tonexty', fillcolor='83d483', line = list(color = '83d483', width = 0),
            showlegend = TRUE, name = list(text = "1.5 C consistent"))

fig <- fig %>% add_trace(x = ~years, y = ~opt, type = 'scatter', mode = 'lines', 
                         line = list(color = "f78c6b", width = 3), showlegend = TRUE, name = list(text = "Optimistic\nnet zero targets"))

fig <- fig %>% add_trace(x = ~years, y = ~historical, type = 'scatter', mode = 'lines', 
                         line = list(color = "black", width = 5), showlegend = FALSE)

fig <- fig %>% layout(title = list(text = paste0('Following the Paris Agreement is Necessary',
                                    '<br>',
                                    '<sup>',
                                    'Emissions and expected warming based on pledges and current policies',
                                    '</sup>'), 
                                   x = 0.1,
                                   y = 0.9,
                                   font = list(
                                     family = "arial",
                                     size = 20)),
                      margin = list(l = 100,
                                    r = 50,
                                    b = 100,
                                    t = 100,
                                    pad = 20), 
         paper_bgcolor="#d2d2d1", plot_bgcolor="#d2d2d1",
         xaxis = list(title = "Year",
                      gridcolor = "white",
                      showgrid = TRUE,
                      showline = FALSE,
                      tickvals = list(1990, 2000, 2010, 2020, 2030, 2040, 2050, 2060, 2070, 2080, 2090, 2100),
                      zeroline = FALSE,
                      tickfont = list(family = "arial", size = 14),
                      titlefont = list(family = "arial", size = 14)),
         yaxis = list(title = "Global Greenhouse Gas Emissions (GtCO2e/Year)",
                      gridcolor = "white",
                      showgrid = TRUE,
                      showline = FALSE,
                      zeroline = FALSE,
                      tickfont = list(family = "arial", size = 14),
                      titlefont = list(family = "arial", size = 14)), 
         legend = list(font = list(family="arial"))) 


fig %>% 
  add_annotations(text="Data source: Climate Analytics and NewClimate Institute and the Climate Action Tracker team.",
                  xref='paper',
                  yref='paper',
                  x=0.6,y=-0.22,
                  showarrow=FALSE, 
                  font = list(family = "arial", size = 11)) %>%
  add_annotations(text="Historical", 
                  xref='paper',
                  yref='paper',
                  x=0.02,y=0.36,
                  showarrow=FALSE, 
                  font = list(family = "arial", size = 17, color='black'))




```



